### ISSUE TITLE
Add support to rez/derez props

### ISSUE THREAD

**Issue by HowardBaxton** [nPoseTeam/nPose-SAT-NOTSAT-Plugin#2]
Currently a work around for waiting to rez props in a SATMSG/NOTSATMSG is to call a notecard to do the work.  Would be nice to be able to rez/derez props directly via SATMSG/NOTSATMSG.

**Comment by LeonaMorro** [comment]
done in 01f0c2b3d85402af0409898cec514439f0494861 new commands ON_SIT, ON_UNSIT
